amcl:
  ros__parameters:
    use_sim_time: true
    min_particles: 500
    max_particles: 2000

map_server:
  ros__parameters:
    use_sim_time: true
    yaml_filename: ""  # set via launch remap

planner_server:
  ros__parameters:
    expected_planner_frequency: 5.0
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"

controller_server:
  ros__parameters:
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller/RegulatedPurePursuitController"
    use_sim_time: true

bt_navigator:
  ros__parameters:
    use_sim_time: true
    default_bt_xml_filename: "navigate_to_pose_w_replanning_and_recovery.xml"

local_costmap:
  ros__parameters:
    update_frequency: 10.0
    publish_frequency: 10.0
    rolling_window: true
    width: 3.0
    height: 3.0
    resolution: 0.05

global_costmap:
  ros__parameters:
    update_frequency: 2.0
    publish_frequency: 2.0
    footprint_padding: 0.01
